### ISSUE TITLE
"Bad TLS Limited" certificate expired, test cases fail

### ISSUE THREAD

**Issue by joernheissler** [wbond/badtls.io#6]
See https://travis-ci.org/wbond/asn1crypto/jobs/484426316 and e.g. https://required-auth.badtls.io:10003/
Cert expired 2019-01-01.

**Comment by wbond** [comment]
The certificates have been regenerated and the blocking hosting issue has been resolved by migrating the site and the Nginx config to a new standalone VM. There is also a new `generate.py --regen-certs` mode to regenerate the server certs, leaving the DH params and CA certs as-is.
